SKILLS_CATALOG = [
    "c++",
    "c",
    "c#",
    "python",
    "java",
    "javascript",
    "typescript",
    "r",
    "sql",
    "php",
    "go",
    "rust",
    "matlab",
    "html",
    "css",
    "react",
    "tailwind css",
    "bootstrap",
    "next.js",
    "node.js",
    "fastapi",
    "django",
    "flask",
    "asp.net",
    "spring boot",
    "mysql",
    "postgresql",
    "mongodb",
    "sqlite",
    "oracle database",
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "pytorch",
    "apache spark",
    "jupyter notebook",
    "rstudio",
    "amazon web services",
    "aws",
    "google cloud",
    "gcp",
    "microsoft azure",
    "azure",
    "docker",
    "kubernetes",
    "git",
    "github",
    "gitlab",
    "red hat enterprise linux",
    "ubuntu",
    "windows server",
    "linux command line",
    "shell scripting",
    "system administration",
    "data structures",
    "algorithms",
    "design patterns",
    "api development",
    "restful services",
    "microservices",
    "debugging",
    "performance optimization",
    "oop",
    "etl pipelines",
    "data warehousing",
    "big data processing",
    "feature engineering",
    "data cleaning",
    "batch processing",
    "streaming systems",
    "apache hadoop",
    "apache kafka",
    "authentication",
    "authorization",
    "encryption",
    "secure coding",
    "oauth",
    "jwt",
    "excel",
]